# Generated by Django 3.0.8 on 2024-01-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000000000, null=True)),
                ('price', models.CharField(max_length=1000000000, null=True)),
                ('ads', models.CharField(max_length=1000000000, null=True)),
                ('revenue', models.CharField(max_length=1000000000, null=True)),
                ('rank', models.CharField(max_length=1000000000, null=True)),
                ('velocity', models.CharField(max_length=1000000000, null=True)),
                ('created', models.CharField(max_length=1000000000, null=True)),
                ('product_link', models.CharField(max_length=1000000000, null=True)),
                ('status', models.CharField(max_length=1000000000, null=True)),
                ('image_file', models.ImageField(default='None', null=True, upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='store_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(auto_now_add=True)),
                ('total_sale', models.CharField(max_length=1000000000, null=True)),
                ('sale_growth_rate', models.CharField(max_length=1000000000, null=True)),
                ('total_order', models.CharField(max_length=1000000000, null=True)),
                ('order_growth_rate', models.CharField(max_length=1000000000, null=True)),
                ('aov', models.CharField(max_length=1000000000, null=True)),
                ('skus', models.CharField(max_length=1000000000, null=True)),
                ('image_file', models.ImageField(default='None', null=True, upload_to='graph_images')),
            ],
        ),
    ]
