# Generated by Django 3.2.23 on 2024-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_detail',
            name='status',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
